In [1]:
import numpy as np
arr =np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [9]:
list1=[]
list2=[]
for i in range(5):
    number1 = int(input())
    number2 = int(input())
    list1.append(number1)
    list2.append(number2)
    array1 = np.array(list1)
    array2= np.array(list2)
    array3=array1+array2

print(array3)
print(np.sort(array3))    





25
1
22
36
11
24
22
1
3
89
[26 58 35 23 92]
[23 26 35 58 92]


In [10]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.size)

(3, 3)
9


In [15]:
arr = np.arange(12)
print("1-D Array",arr)
arr = arr.reshape(4,3)
print(" 2-D Array",arr)

1-D Array [ 0  1  2  3  4  5  6  7  8  9 10 11]
 2-D Array [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [16]:
f = np.array([1,2,3])
g = np.array([4,5,6])
print('Horizontal Append:', np.hstack((f, g)))
print('Vertical Append:', np.vstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]
Vertical Append: [[1 2 3]
 [4 5 6]]


In [18]:
arr = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18])
print('Original Numpy Array : ' , arr)

uniqueValues, occurCount = np.unique(arr, return_counts=True)
print("Unique Values : " , uniqueValues)
print("Occurrence Count : ", occurCount)



Original Numpy Array :  [11 11 12 13 14 15 16 17 12 13 11 14 18]
Unique Values :  [11 12 13 14 15 16 17 18]
Occurrence Count :  [3 2 2 2 1 1 1 1]
